# Generated by Django 4.0.2 on 2024-03-06 17:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_alter_event_category_alter_event_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userevent",
            name="liked",
        ),
    ]
