# Generated by Django 5.0.2 on 2024-02-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0002_remove_event_date_time_remove_event_nyu_discount_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
