# Generated by Django 4.0.2 on 2024-03-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_event_availability"),
        ("backend", "0003_remove_userevent_liked"),
    ]

    operations = []
