# Generated by Django 4.0.2 on 2024-03-18 03:09

import backend.models
import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=backend.storage.OverwriteStorage(),
                upload_to=backend.models.profile_avatar_name,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
