# Generated by Django 4.0.2 on 2024-03-18 02:43

import backend.models
import backend.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                storage=backend.storage.OverwriteStorage(),
                upload_to=backend.models.profile_avatar_name,
            ),
        ),
    ]
