# Generated by Django 5.0.2 on 2024-03-19 17:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_profile_avatar_alter_profile_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="comment",
            new_name="review_text",
        ),
    ]
