# Generated by Django 4.0.2 on 2024-03-22 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_merge_20240322_1431"),
        ("backend", "0009_suspendeduser_banneduser"),
    ]

    operations = []
