# Generated by Django 4.0.2 on 2024-03-30 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_suspendeduser_banneduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
    ]
