# Generated by Django 4.2.9 on 2024-03-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_suspendeduser_banneduser"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
