# Generated by Django 4.2.9 on 2024-03-30 05:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0010_review_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.AddField(
            model_name="review",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
