# Generated by Django 4.0.2 on 2024-03-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_chatroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="receiver_room_slug",
            field=models.TextField(),
        ),
    ]
