# Generated by Django 4.2.9 on 2024-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_remove_review_likes_review_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="likes",
        ),
        migrations.AddField(
            model_name="review",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
