# Generated by Django 4.2.9 on 2024-03-30 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0012_remove_review_likes_review_likes_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
