# Generated by Django 4.0.2 on 2024-04-06 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_review_reply_count_replytoreview"),
        ("backend", "0014_room3_chatroom3"),
    ]

    operations = []
