# Generated by Django 4.0.2 on 2024-04-10 20:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0015_user_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="replytoreview",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="reply_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="replytoreview",
            name="likes_count",
            field=models.IntegerField(default=0),
        ),
    ]
