# Generated by Django 4.2.9 on 2024-04-14 22:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0016_replytoreview_liked_by_replytoreview_likes_count"),
        ("backend", "0016_report"),
    ]

    operations = []
