# Generated by Django 4.0.2 on 2024-04-17 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_remove_event_external_link_event_external_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="external_links",
            new_name="external_link",
        ),
    ]
