# Generated by Django 4.0.2 on 2024-04-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_rename_external_links_event_external_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='external_link',
            field=models.URLField(blank=True),
        ),
    ]
