# Generated by Django 4.0.2 on 2024-04-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_reportreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='replytoreview',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='replytoreview',
            name='report_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='report_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
