# Generated by Django 4.2.9 on 2024-04-19 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0019_replytoreview_is_reported_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="replytoreview",
            name="report_timeout",
        ),
        migrations.RemoveField(
            model_name="review",
            name="report_timeout",
        ),
    ]
