# Generated by Django 4.0.2 on 2024-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_event_external_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='external_link',
        ),
        migrations.AddField(
            model_name='event',
            name='external_links',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
