# Generated by Django 4.0.2 on 2024-04-18 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0017_merge_20240414_2215"),
        ("backend", "0020_remove_event_external_link_event_external_links"),
    ]

    operations = []
