# Generated by Django 4.0.2 on 2024-04-25 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0020_remove_replytoreview_report_timeout_and_more"),
        ("backend", "0021_merge_20240418_1612"),
    ]

    operations = []
