# Generated by Django 4.2.9 on 2024-04-21 22:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0020_remove_replytoreview_report_timeout_and_more"),
        ("backend", "0022_remove_banneduser_banned_at_and_more"),
    ]

    operations = []
